language: node_js
node_js:
  - 12
services:
  - docker
install:
  - echo "Nothing to install"
before_script:
  - echo "No tests"
script:
  - docker --version
  - docker build . -t udagram-frontend
  - docker tag udagram-frontend asafalkhasov/udagram-frontend:$TRAVIS_JOB_NUMBER

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push asafalkhasov/udagram-frontend:$TRAVIS_JOB_NUMBER